baseurl = "https://blog.puckwang.com/"
title = "Puck's Blog"
author = "Puck Wang"
copyright = "Copyright © 2017-2019, Puck Wang; all rights reserved."
canonifyurls = true
paginate = 10
theme = "silhouette-hugo"

pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "vs"

disqusShortname = "puckwang"
googleAnalytics = "UA-44442837-9"

[Params]
author = "Puck Wang"
images = ["/images/og_image.png"]
introDescription = "真正全端開發者的知識庫分享平台"
contentSharing = "Opinions expressed here are my own and may not reflect those of the company I work for, or the people I work with."
data_format = "2006-01-02 15:04:05"

[[Params.socials]]
    icon = "fab fa-facebook-square"
    link = "//www.facebook.com/puckwang14"

[[Params.socials]]
    icon = "fab fa-twitter"
    link = "//twitter.com/puckwang14"

[[Params.socials]]
    icon = "fab fa-github"
    link = "//github.com/puckwang"

[[Params.socials]]
    icon = "fab fa-linkedin"
    link = "//linkedin.com/in/joshua-hu-12290a43"

[[Params.socials]]
    icon = "fab fa-stack-overflow"
    link = "//stackoverflow.com/users/7699156/puckwang?tab=profile"

[[Params.menus]]
    name = "Home"
    link = "/"

[[Params.menus]]
    name = "關於我"
    link = "/about"

[[Params.menus]]
    name = "Side Projects"
    link = "/projects"

[[Params.menus]]
    name = "旅遊"
    link = "/travels"

[[Params.menus]]
    name = "攝影"
    link = "/photography"
